# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-12 18:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('gmail', models.CharField(max_length=500)),
                ('password', models.CharField(max_length=1000)),
                ('list_video', models.CharField(max_length=5000)),
            ],
        ),
    ]
