# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-12 18:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='list_video',
            field=models.CharField(max_length=5000, null=True),
        ),
    ]
