# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-14 17:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0003_auto_20170612_1827'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
