# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-17 14:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0005_videolist'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VideoList',
            new_name='Video',
        ),
    ]
