# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-17 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0006_auto_20170617_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='date',
            field=models.DateField(),
        ),
    ]
